name: Generate Directory Markdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run Directory Tree Generator
        uses: DenizAltunkapan/directory-tree-generator@v2
        with:
          path: "backend,frontend"
          extensions: ".java,.html,.ts,.scss"
          show-extensions: true

      - name: Checkout or create Dependabot-style branch
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

          BRANCH_NAME=dependabot/directory-update

          # Pr√ºfen, ob Branch remote existiert
          if git ls-remote --exit-code origin $BRANCH_NAME; then
            git fetch origin $BRANCH_NAME
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Commit changes if there are any
        run: |
          git add DIRECTORY.md
          # commit only if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update DIRECTORY.md"
          else
            echo "No changes to commit"
          fi

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dependabot/directory-update
          base: main
          title: "Bump directory structure (auto-generated)"
          body: "This PR updates DIRECTORY.md automatically."
          draft: false
          fail-on-empty-changes: false
